### ISSUE TITLE
Add a License.

### ISSUE THREAD

**Issue by NightlyNexus** [git-mad/TopicBingo#4]
Consider adding a license to the project.  I would go with GPLv3, so any distributors of the app will have to provide source code.

**Comment by dgreenhalgh** [comment]
This is a good call. We'd like to publish to the Play Store and are currently considering the logistics involved in publishing as an open organization (who gets credit for dev/design, etc.). We should be able to better answer these questions by the next meeting.

**Comment by NightlyNexus** [comment]
More importantly, deciding who ponies up the $25 for the publishing fee.  :)
